const invoices: InvoiceType[] = [
  {
    _id: "66df4bf81fd969ddf15ff2ca",
    invoiceNumber: "218",
    createdAt: "1725910008513",
    updatedAt: "1725910008513",
    date: "2024-09-09T00:00:00.000Z",
    customerId: {
      _id: "66c72bf17e681f28cc4ec752",
      firstName: "Kay",
      lastName: "Rambo",
      address: {
        _id: "66c72bf17e681f28cc4ec752",
        street: "123 Main St",
        city: "Anytown",
        state: "Anystate",
        zip: "12345",
        country: "USA",
        unit: "Apt 1",
      },
      businessName: "Kay's Business",
      email: "kay.rambo@example.com",
      invoices: [],
      phone: "123-456-7890",
      properties: [],
      workOrders: [],
    },
    workOrders: [
      {
        _id: "exampleWorkOrderId",
        charged: true,
        comments: "Example comment",
        completed: true,
        completedBy: "Technician Name",
        customerId: {
          _id: "66c72bf17e681f28cc4ec752",
          firstName: "Kay",
          lastName: "Rambo",
          address: {
            _id: "66c72bf17e681f28cc4ec752",
            street: "123 Main St",
            city: "Anytown",
            state: "Anystate",
            zip: "12345",
            country: "USA",
            unit: "Apt 1",
          },
          businessName: "Kay's Business",
          email: "kay.rambo@example.com",
          invoices: [],
          phone: "123-456-7890",
          properties: [],
          workOrders: [],
        },
        date: "2024-09-09T00:00:00.000Z",
        description: "Example work order description",
        updatedAt: "2024-09-09T00:00:00.000Z",
      },
    ],
    quote: 0,
    total: 10000,
    charged: true,
    paid: true,
    materialsCost: 0,
    materialsCostDescription: "n/a",
    comments: "Reinstalled door closer clips with new hardware.",
    laborItems: [],
  },
  {
    customerId: {
      _id: "66c7b5bd85b72e99e1960388",
      firstName: "David",
      lastName: "Poggi",
      address: "456 Elm St",
      businessName: "David's Business",
      email: "david.poggi@example.com",
      invoices: [],
      phone: "987-654-3210",
    },
    te: "2024-09-09T00:00:00.000Z",
    customerId: {
      _id: "66c7b5bd85b72e99e1960388",
      firstName: "David",
      lastName: "Poggi",
    },
    workOrders: [],
    quote: 7500,
    total: 7500,
    charged: true,
    paid: true,
    materialsCost: 0,
    customerId: {
      _id: "66c878ea0dff3ffa0b88e022",
      firstName: "Mike",
      lastName: "n/a",
      address: "789 Oak St",
      businessName: "Mike's Business",
      email: "mike@example.com",
      invoices: [],
      phone: "555-555-5555",
    },
    _id: "66df4eaf1fd969ddf15ff2e3",
    invoiceNumber: "219",
    createdAt: "1725910703971",
    updatedAt: "1725911940156",
    date: "2024-09-09T00:00:00.000Z",
    customerId: {
      _id: "66c878ea0dff3ffa0b88e022",
      firstName: "Mike",
      lastName: "n/a",
    },
    workOrders: [],
    customerId: {
      _id: "66da31c923df402b35e0e092",
      firstName: "Anna",
      lastName: "Marosi",
      address: null,
      businessName: "Unknown",
      email: "unknown@example.com",
      invoices: [],
      phone: "111-222-3333",
      properties: [],
      workOrders: [],
    },
    materialsCost: 0,
    materialsCostDescription: "n/a",
    comments: "Removed, cleaned, reinstalled ice maker.",
    laborItems: [],
  },
  {
    _id: "66df52ecbdfcf2b9536e98e4",
    invoiceNumber: "220",
    createdAt: "1725911788830",
    updatedAt: "1725911788830",
    date: "2024-09-09T00:00:00.000Z",
    total: 0,
    paid: true,

    workOrders: [
      {
        _id: "aklshdlaskhdasdjlkas",
        date: "2024-09-09T00:00:00.000Z",
        description: "Work order description",
        updatedAt: "2024-09-09T00:00:00.000Z",
        lastUpdated: "2024-09-09T00:00:00.000Z",
        paid: true,
        quote: 0,
        total: 5000,
        type: "Work Order",
        propertyId: {
          _id: "examplePropertyId",
          propertyAddress: {
            _id: "examplePropertyId",
            street: "123 Example St",
            city: "Example City",
            state: "Example State",
            zip: "12345",
            country: "Example Country",
            unit: "Example Unit",
          },
          agent: {
            _id: "exampleAgentId",
            firstName: "exampleFirstName",
            lastName: "exampleLastName",
            email: "exampleEmail",
            phone: "examplePhone",
            address: {
              _id: "exampleAddressId",
              street: "123 Example St",
              city: "Example City",
              state: "Example State",
              zip: "12345",
              country: "Example Country",
              unit: "Example Unit",
            },
            businessName: "exampleBusinessName",
            invoices: [],
            properties: [],
            workOrders: [],
          },
          propertyDescription: "exampleDescription",
          propertyName: "examplePropertyName",
          s3FolderKey: "exampleS3FolderKey",
        },
        invoices: [],
        charged: true,
        comments: "Fixed issue",
        completed: true,
        completedBy: "Technician Name",

        customerId: {
          _id: "66da31c923df402b35e0e092",
          firstName: "Anna",
          lastName: "Marosi",

          workOrders: [],
          businessName: "Unknown",
          email: "unknown@example.com",
          invoices: [],
          phone: "111-222-3333",
          properties: [],
          address: {
            _id: "66da31c923df402b35e0e092",
            street: "123 Main St",
            city: "Anytown",
            state: "Anystate",
            zip: "12345",
            country: "USA",
            unit: "Apt 1",
          },
        },
      },
    ],
    quote: 0,
    charged: true,
    materialsCost: 0,
    materialsCostDescription: "n/a",
    comments:
      "Diagnosed malfunctioning dishwasher drain pump. Removed dishwasher from house.",
    laborItems: [],
  },
];
